name: Build main branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ self-hosted, amd64, noble, xlarge-extra ]
          - [ self-hosted, arm64, noble, large-extra ]
    with:
      runner: "${{ toJSON(matrix.runner) }}"
      init-build-script: '.github/workflows/init-build.sh'
      publish-channel: 'latest/edge' # Add track if needed, e.g., 24/latest/edge
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN }}
